### PR TITLE
Add topic tooltips

### PR DESCRIPTION
**Pull request by codyjames**

### CODE REVIEW

**Comment by codyjames** [comment]
@jerodsanto Wanna take a look at this?

**Comment by jerodsanto** [comment]
@codyjames did some slight refactoring. Let me know if you have any questions on that front.

Left to do: I noticed you were using `topic.name` instead of `topic.slug` in the tooltip. I prefer to keep it uniform with the listed topics in the toolbar, so I switched that. Now the margin|padding on the tooltip seems a bit off:

2018-04-18 at 9 39 am

I'd also like to make all of our tooltips disappear when clicking anywhere in the viewport that isn't the tooltip itself, but maybe that's a separate feature/task.

**Comment by adamstac** [comment]
@codyjames are those tooltips still the same size as above? If so, I think they should be a little smaller.

**Comment by codyjames** [comment]
@adamstac It's just the standard tooltip sizing. Do you want me to reduce the size for all tooltip text or just for this area?

**Comment by adamstac** [comment]
For this instance only. Seems a little large to me.

**Comment by codyjames** [comment]
@jerodsanto I tried out a simple method for closing the tooltips when clicking elsewhere. wanna take a peak at it?

**Comment by codyjames** [comment]
@jerodsanto Fix is up!

**Pull request merged**
