### PR TITLE
W3c html validation fixes

### PR DESCRIPTION
**Pull request by ken-kost**
Fixes for #270

### CODE REVIEW

**Comment by jerodsanto** [comment]
This is cool! Did you load up the player and make sure everything looks the same? Also, what's wrong with <section>?

**Comment by jerodsanto** [comment]
Sorry html tags narfled it. What’s wrong with section elements?-Jerod(sent on the go)On May 4, 2023, at 12:27 PM, Kenneth Kostrešević ***@***.***> wrote:﻿

This is cool! Did you load up the player and make sure everything looks the same? Also, what's wrong with
?

What's wrong with question mark?
I haven't checked the player, I will try tomorrow and I'll report back. 👍

**Comment by ken-kost** [comment]
> What’s wrong with section elements?

I changed it to div because of the warning

`Warning: Section lacks heading. Consider using h2-h6 elements to [add identifying headings to all sections](https://www.w3.org/wiki/HTML/Usage/Headings/Missing), or else use a div element instead for any cases where no heading is needed.`

**Comment by ken-kost** [comment]
@jerodsanto I tried to test out the player and it seems fine but I can not be 100% sure since I don't have db locally. Could you check, or give me pointers on how to?

**Comment by jerodsanto** [comment]
@all-contributors please add @ken-kost for code

**Pull request merged**
