### PR TITLE
Remove unused mark_for_deletion functionality

### PR DESCRIPTION
**Pull request by dougal**
Found some unused functionality while spelunking the codebase. Of course this might be used with tools you have not published. Below is what I wrote in the first commit:

---

* The functionality provided by this was never used in other modules.
* Record deletion is always done using Repo.delete directly.
* No tests exercised this code.
* Code is almost identical to same [pattern shown in Ecto.Changelog docs](https://hexdocs.pm/ecto/Ecto.Changeset.html#module-on-replace).
* Code appears to have been pasted from model-to-model as more were added.

---

Thanks for open-sourcing, I learnt a lot, including the `mark_for_deletion` pattern.

### CODE REVIEW

**Comment by dougal** [comment]
s/methods/functions/

**Comment by jerodsanto** [comment]
Thanks for contributing! Code spelunking is fun 🔍

I haven't looked at this for awhile, but I'm _pretty sure_ that these are necessary as the related `Changelog.Episode` will call `cast_assoc` when its changeset is processed via the admin form. That, in turn, calls `changeset` on the associated records, which calls `mark_for_deletion`. If the virtual attribute has been set via the params, the record will be deleted.

You are totally right that I haven't tested this well (there are not many tests in the admin), but you could test manually (or add tests!) by setting up an episode with some hosts/guests/channels/sponsors and then try deleting those associations on your branch. (I don't think it'll work.)

Thanks again, I love how many folks are taking the code for a spin! 💚

**Comment by dougal** [comment]
Yes, you are right, these are in fact used. In the templates the `:delete` virtual field is referenced for use in [checkboxes for the deletion of things like guests or hosts from episodes](https://github.com/thechangelog/changelog.com/blob/master/web/templates/admin/episode/_form.html.eex#L112).

If only I'd noticed this I could have submitted some tests instead. Thanks for the reply.

**Comment by jerodsanto** [comment]
No worries, it is subtle and undocumented.

**Pull request closed without merging**
