### PR TITLE
Update instances of "Github" to "GitHub"

### PR DESCRIPTION
**Pull request by tarebyte**
Apologies for the pageantry, but I realized this site was open source and I couldn't resist 😄

### CODE REVIEW

**Comment by adamstac** [comment]
Love it! Come hang with us ~> https://changelog.com/community

**Comment by tarebyte** [comment]
> Love it! Come hang with us

That's where I found the typo! I was coming to join 😆

**Comment by jerodsanto** [comment]
💚💚💚

**Comment by adamstac** [comment]
> That's where I found the typo! I was coming to join 😆

I thought so, but wanted to make sure! Stoked you found that page to join the community.

**Pull request merged**
