### PR TITLE
Sponsor page rework [WIP]

### PR DESCRIPTION
**Pull request by codyjames**
- [x] Cody: Create Dropbox Paper doc detailing needed image sizes.
- [x] Cody: Figure out Line Clamp solution.
- [x] Cody: Clean up button groups and logo grids on other marketing pages.
- [x] Cody: On mobile, move slider pagination dots to above slider.
- [x] @adamstac: Create images, refine content
- [x] @jerodsanto: Make sponorship previews dynamic
- [ ] [Post-launch] Browser/device testing

### CODE REVIEW

**Comment by adamstac** [comment]
@codyjames I decided to pull the partner slider since content for partner stories and fleshing those out is taking more time than I expected (PR and approvals). I updated all the content and moved the slider to a partial that's commented out for now.

Can you review and merge when you get a chance?

**Comment by codyjames** [comment]
@adamstac I'll take a look this week!

**Comment by jerodsanto** [comment]
There are some pretty hairy merge conflicts on this branch. Want me to take a pass at a merge before you do, @codyjames?

**Comment by codyjames** [comment]
@jerodsanto That'd be fantastic.

**Comment by jerodsanto** [comment]
@codyjames it's all yours ✅

**Pull request merged**
