### PR TITLE
Feat/feed specific topics

### PR DESCRIPTION
**Pull request by hailelagi**
addresses: https://github.com/thechangelog/changelog.com/issues/384

### CODE REVIEW

**Comment by hailelagi** [comment]
Hi @jerodsanto I kind of dropped off on this last year sorry about that, but I really want to pick it back, although it's been quite awhile! If this is something useful I'll try to dive back in! cheers

**Comment by jerodsanto** [comment]
Yeah man, let's pick it back up!

**Comment by gerhard** [comment]
There are a few failing tests: https://app.circleci.com/pipelines/github/thechangelog/changelog.com/812/workflows/db6d709a-3d33-49e4-9e22-b027d7fe1712/jobs/5532?invite=true#step-105-1171

When they get fixed, what needs to happen before this can get merged @jerodsanto?

**Comment by hailelagi** [comment]
I have a few changes on my local host, I think I can close this out this weekend

**Comment by Nezteb** [comment]
Alright @hailelagi @gerhard I've got a PR ready for reviews to merge into this one: https://github.com/hailelagi/changelog.com/pull/1

**Pull request closed without merging**
