### PR TITLE
docker-compose-erize app along with supporting services

### PR DESCRIPTION
**Pull request by akoutmos**
Getting the whole application running in docker compose along with Prometheus and Grafana

### CODE REVIEW

**Comment by jerodsanto** [comment]
@gerhard are there any production implications of unplugging the `Logger` and `Telemetry` plugs for requests to `/metrics` that I'm not thinking of?

**Comment by gerhard** [comment]
I can't think of any.

If anything, we may want to restrict access to `/metrics` requests in prod. What would be the easiest way of doing that @akoutmos?

**Comment by akoutmos** [comment]
I'll add that validation step right in this PR @gerhard and @jerodsanto. All we'll need to do is add an additional env var configuration in k8s so that Prom can scrape those protected metrics. Sound good?

**Comment by gerhard** [comment]
Yup, that sounds good to me 👍🏻

**Comment by jerodsanto** [comment]
Thanks for updating the README too 👏

**Pull request merged**
