### PR TITLE
Disable capitalization in profile fields

### PR DESCRIPTION
**Pull request by mcdado**
Just signed up from mobile, couldn't stand the autocapitalization in form fields.

This is totally untested and I have no idea how to build and run Elixir to test it, I just followed this page:
https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#text_input/3

Do as you wish with this PR 😉

### CODE REVIEW

**Comment by jerodsanto** [comment]
I don't remember if this was a design decision or just an implementation detail. @adamstac or @codyjames do you have strong opinions on this?

**Comment by mcdado** [comment]
Keep in mind signing up from mobile.
And capitalising social handles and URLs doesn't make much sense to me 😉

**Comment by codyjames** [comment]
This is just fixing the thing where the mobile OS or Browser auto-capitalizes the first letter of input? If so, yeah, this is great. Good catch!

**Comment by mcdado** [comment]
Yep! Adding `autocapitalize="none"` to an `<input>` field disables the capitalization entirely.
But as I mentioned before I don't even know if this works as it should in the context of Elixir.

**Pull request merged**
