### PR TITLE
chore: New contributing guide

### LINKED ISSUE #324: Docker: Get ElixirLS fully working in dev
Running the project on Docker has some inconsistencies. I'll try to note them as I go. This is one where we should make sure ElixirLS can run fully during development.

Gotta polish up the Docker way of running this stuff so Jerod can start using it ;)

```
{
	"resource": "/root/changelog.com/mix.exs",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "an exception was raised:\n    ** (Mix.Error)   Could not run `make`.\n  Please check if `make` and either `clang` or `gcc` are installed\n\n        /root/changelog.com/deps/cmark/mix.exs:88: Mix.Tasks.Compile.Cmark.run/1\n        (mix 1.10.3) lib/mix/task.ex:330: Mix.Task.run_task/3\n        (mix 1.10.3) lib/mix/tasks/compile.all.ex:76: Mix.Tasks.Compile.All.run_compiler/2\n        (mix 1.10.3) lib/mix/tasks/compile.all.ex:56: Mix.Tasks.Compile.All.do_compile/4\n        (mix 1.10.3) lib/mix/tasks/compile.all.ex:27: anonymous fn/2 in Mix.Tasks.Compile.All.run/1\n        (mix 1.10.3) lib/mix/tasks/compile.all.ex:43: Mix.Tasks.Compile.All.with_logger_app/2\n        (mix 1.10.3) lib/mix/task.ex:330: Mix.Task.run_task/3\n        (mix 1.10.3) lib/mix/tasks/compile.ex:96: Mix.Tasks.Compile.run/1",
	"source": "ElixirLS",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

### LINKED ISSUE #325: Docker: Get file watching/live reload working for dev
Not sure about the exact reason, but with the standard docker compose I'm not getting live reloads. Might be a missing inotify-tools or something. Should take a look.

### LINKED ISSUE #326: Docker: Make it easier to run mix tests
I currently run this: `DB_URL="ecto://postgres@db:5432/changelog_test" mix test`

There was some additional setup to get there as well if I recall. There are some things that could be cleaned up there.

### PR DESCRIPTION
**Pull request by gerhard**
+ 🧘 simplifies `README.md`
+ ✨ new contribution workflow; [inspired by dagger](https://github.com/dagger/dagger/blob/89234a3fe1446780d59871d311f5df62d99718b6/docs/partials/_contributing.md)
+ 👮 add missing dependencies: PostgreSQL, Node.js & Yarn
+ 🕵️ mention deps version that we are currently running in production
+ 🗑 remove Docker instructions & docker-compose tooling (they do not work, and since we are moving away from that approach, this is a step in that direction)
+ 💻 add instructions on how to setup the app for local development (just tested on a clean macOS 12)

Somewhat related to the above improvements, we now require all commits to be `Signed-off-by: <NAME> <EMAIL>`. This is enforced at a PR level, added as a [branch protection rule](https://github.com/thechangelog/changelog.com/settings/branch_protection_rules/1495659) via a [GitHub DCO app install](https://github.com/organizations/thechangelog/settings/installations/31181965).

Closes https://github.com/thechangelog/changelog.com/issues/324 🙏 **help wanted with Linux**
Closes https://github.com/thechangelog/changelog.com/issues/325
Closes https://github.com/thechangelog/changelog.com/issues/326

### CODE REVIEW

**Comment by jerodsanto** [comment]
What do we gain with the `Signed-off-by` requirement?

**Comment by jerodsanto** [comment]
Okay I will try to find a way to configure git so that I always sign off on my commits. When it comes to my own code:

> I'm Jerod Santo, and I approve this message 👍

**Comment by adamstac** [comment]
The guide is pretty good. There are a few hurdles that weren't mentioned, but otherwise quite thorough.

However, at the end of the setup when I run the app, I get this error in the logs and the app errors with

~~~
UndefinedFunctionError at GET /
function Cmark.Nif.render/3 is undefined (module Cmark.Nif is not available)
~~~

This is what's in the running app log.

~~~
[error] Process #PID<0.859.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/adamstacoviak/Code/changelog.com/_build/dev/lib/cmark/priv/cmark.so, 0x0002): tried: \'/Users/adamstacoviak/Code/changelog.com/_build/dev/lib/cmark/priv/cmark.so\' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), \'/Users/adamstacoviak/Code/changelog.com/deps/cmark/priv/cmark.so\' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))\''}}
    (cmark 0.10.0) lib/cmark/nif.ex:9: Cmark.Nif.init/0
    (kernel 8.5.1) code_server.erl:1317: anonymous fn/1 in :code_server.handle_on_load/5
[error] Process #PID<0.864.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/adamstacoviak/Code/changelog.com/_build/dev/lib/cmark/priv/cmark.so, 0x0002): tried: \'/Users/adamstacoviak/Code/changelog.com/_build/dev/lib/cmark/priv/cmark.so\' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), \'/Users/adamstacoviak/Code/changelog.com/deps/cmark/priv/cmark.so\' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))\''}}
    (cmark 0.10.0) lib/cmark/nif.ex:9: Cmark.Nif.init/0
    (kernel 8.5.1) code_server.erl:1317: anonymous fn/1 in :code_server.handle_on_load/5
~~~

**Comment by jamietanna** [comment]
If you're still looking for a Linux user to give a hand with this, I'm happy to help!

**Comment by gerhard** [comment]
> The guide is pretty good. There are a few hurdles that weren't mentioned, but otherwise quite thorough.

What is missing @adamstac? I am aware of ImageMagick - coming up next.

> @adamstac However, at the end of the setup when I run the app, I get this error in the logs and the app errors with

As @jerodsanto mentioned, that library was compiled on an Intel Mac, but you are trying to run it on ARM Mac. If our understanding is correct, this should fix it @adamstac:

```console
rm -fr _build
mix phx.server
```

**Comment by gerhard** [comment]
> @jerodsanto Is there something special you need to do with gcc or clang to compile on M* Macs, perhaps?

I just followed the local setup on an ARM Mac and everything worked as expected. Works on my other machine 💻

**Pull request merged**
