### PR TITLE
Enable team members to replace changelog_dev with a prod db dump

### PR DESCRIPTION
**Pull request by gerhard**
There is a single command to run:

    just restore-dev-db-from-prod

This implies that:
- direnv.net is hooked into the shell -`just envrc-secrets` has already run & `.envrc.secrets` exists
- Posgres 16.5 has installed using `just install`

Part of this change we exposed a few more private recipes and made it clear who they are meant for:
- `contributor` means anyone that wants to play with this repo locally
- `team` means Adam, Jerod & Gerhard

We also added `just add-oban-pro-repo` so that we make this integration easier for team members - I always forget about it!

---

## How does this work on a fresh Mac 💻 ?

https://github.com/user-attachments/assets/9493fe44-2423-4601-b481-8184558b8a6c

### CODE REVIEW

**Comment by gerhard** [comment]
Anything that you would like me to change about this DX @adamstac @jerodsanto before merging?

**Comment by jerodsanto** [comment]
Overall this LGTM but I'm curious about the Postgres stuff. I have pg installed via asdf so I think the homebrew path stuff won't cut it...

**Comment by gerhard** [comment]
Would you be OK to also install Postgres using Homebrew **in addition to** asdf?

If not, that's OK, I can try to get this to work with an already installed Postgres.

While I didn't capture this in https://github.com/thechangelog/changelog.com/pull/521, the reason why I removed Postgres install via asdf is that the `icu4c` dependency stopped working on macOS 14.7. I was hitting the same compilation issues on both ARM & Intel. I could try it out Postgres 16 via asdf again in case the issue was fixed, but since `brew install postgres@16` was there & it worked, that was the path of least resistance at the time.

**Comment by jerodsanto** [comment]
I'd prefer we focus in on just one installer and since we're using `.tool-versions` I think it should be asdf. I do have postgres 16 installed via asdf, btw, and no issues with `icu4c`, fwiw...

**Comment by gerhard** [comment]
OK, Postgres 16.5 (same as prod) is now managed by asdf.

Want to try running this locally now @jerodsanto ?

**Comment by jerodsanto** [comment]
It works!

**Pull request merged**
