### PR TITLE
✈️ Migrate changelog.com to Fly.io ✈️

### PR DESCRIPTION
**Pull request by gerhard**
This is the story of migrating changelog.com from LKE to fly.io, [a PaaS where _Phoenix screams_](https://fly.io/blog/how-we-got-to-liveview/).

The main reason was to challenge assumptions (mostly mine) and experiment with doing things differently, in a simpler way. I am genuinely curious to discover what we will actually miss most from our Kubernetes setup, what alternatives are there (some may be better!), and most importantly how well does this actually work in practice. I still think that `AND` propositions are better than `OR`, and while I don't rule Kubernetes from our future, now is a good time to spring clean and shake things up a bit 😉

Also, I am heeding wise advice, and migrating Postgres to [a managed fly.io one](https://fly.io/docs/reference/postgres/):

<a href="https://changelog.com/shipit/44#t=8:32" target="_blank">image</a>

Most of the changes I ran imperatively, by issuing `fly` commands. While I tried to capture some of them in the latest implementation of [Dagger 0.2.0](https://dagger.io), at some point I started getting slowed down because I was trying to reconcile two things at once. I have since shifted focus to `fly` only in order to achieve the primary goal of migrating changelog.com to fly.io quicker.

The backstory is that we are currently running on Linode Kubernetes Engine 1.20 which will be forcefully migrated to 1.21 on March 17, 2022 (so in less than 48 hours). K8s 1.20 is EOL and upgrades + security patches are no longer available. While  we started a 1.22 K8s LKE cluster in the [2022 dir](https://github.com/thechangelog/changelog.com/tree/e67acd1d054ef2277b2a1a82317a607884ac2202/2022), we didn't finish that migration - life happened - and at this point the quickest thing is to migrate to fly.io. In all honesty, we have been talking about this for months: Ship It [#44](https://changelog.com/shipit/44), [#43](https://changelog.com/shipit/43), [#40](https://changelog.com/shipit/40) & [#31](https://changelog.com/shipit/31). This is the simplest thing right now. We will make some new friends - 👋🏻 @mrkurt @chrismccord @brainlid 👋🏻 - and most likely have a great story to share.

OK, let's get this party started!

## What happened so far?

1. [Create a 2-node PostgreSQL 14 cluster on fly.io](https://github.com/thechangelog/changelog.com/pull/407/files#diff-7f9a218d671a3accf380cc0a32121c588ecec518e18dabdb544b83f3f64fb8a9R86-R93)
2. Import `prod-2021-04_changelog_2022-03-13T13.00.09Z.sql`, [an hourly backup running in our current LKE production origin](https://github.com/thechangelog/changelog.com/blob/423e67ddca91e640d62e58927686a9fcb2728818/2021/manifests/changelog/jobs.yml#L114)
3. [Load all secrets from LastPass into fly.io](https://github.com/thechangelog/changelog.com/pull/407/files#diff-a993be8db3f07f33dccfe38d016515cf7414b08d0f7db028b0f9dc685ef5fe57R361-R366)
4. [Deploy changelog.com app as a container image](https://github.com/thechangelog/changelog.com/pull/407/files#diff-e9f3c735c22cbe0df3a4de0a5c2e41735bbc620d63f328b4b6efeca4b4885d35)
5. Scaled the app instance to `dedicated-cpu-4x` (app was crashing due to OOM errors)

The app instance is currently running at https://changelog-2022-03-13.fly.dev/ 🙌🏻

## What happens next?

- [x] [Figure out why we cannot login as admins via email](https://github.com/thechangelog/changelog.com/pull/407/commits/06f2bbc0f583d9c37d0e83743d79cfce04aaccb9)
- [x] Figure out how to re-import `changelog` db from local backup file → running the `psql` command will fail, the db needs to be re-created for this to work
```
fly scale count 0
fly postgres connect postgres-2022-03-12
drop database changelog with (FORCE);
create database changelog;
flyctl proxy 5432 -a postgres-2022-03-12
psql -h 127.0.0.1 changelog postgres < ~/Downloads/prod-2021-04_changelog_2022-03-15T23.24.19Z.sql
fly scale count 1
```
- Figure out why this is happening on app boot → this feels like a @akoutmos task
<details>
  <summary><code>TelemetryMetricsPrometheus.Core.EventHandler</code> has failed and has been detached</summary>
  <pre>
20:31:29.901 [error] Handler {TelemetryMetricsPrometheus.Core.EventHandler, #PID<0.518.0>,
 [:changelog, :prom_ex, :oban, :init, :circuit, :backoff, :milliseconds]} has failed and has been detached. Class=:error
Reason={:badkey, :circuit_backoff,
 %Oban.Config{
   dispatch_cooldown: 5,
   engine: Oban.Queue.BasicEngine,
   get_dynamic_repo: nil,
   log: false,
   name: Oban,
   node: "31eb7755",
   notifier: Oban.Notifiers.Postgres,
   plugins: [
     {Oban.Plugins.Cron,
      [
        timezone: "US/Central",
        crontab: [
          {"0 4 * * *", Changelog.ObanWorkers.StatsProcessor},
          {"0 3 * * *", Changelog.ObanWorkers.SlackImporter},
          {"* * * * *", Changelog.ObanWorkers.NewsPublisher}
        ]
      ]},
     Oban.Plugins.Stager,
     Oban.Plugins.Pruner
   ],
   prefix: "public",
   queues: [comment_notifier: [limit: 10], scheduled: [limit: 5]],
   repo: Changelog.Repo,
   shutdown_grace_period: 15000
 }}
Stacktrace=[
  {PromEx.Plugins.Oban, :"-oban_supervisor_init_event_metrics/2-fun-2-", 2,
   [file: 'lib/prom_ex/plugins/oban.ex', line: 389]},
  {TelemetryMetricsPrometheus.Core.EventHandler, :get_measurement, 3,
   [file: 'lib/core/event_handler.ex', line: 63]},
  {TelemetryMetricsPrometheus.Core.LastValue, :handle_event, 4,
   [file: 'lib/core/last_value.ex', line: 56]},
  {:telemetry, :"-execute/3-fun-0-", 4,
   [file: '/app/deps/telemetry/src/telemetry.erl', line: 150]},
  {:lists, :foreach, 2, [file: 'lists.erl', line: 1342]},
  {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
]
  </pre>
</details>

- [x] [Configure GitHub Actions to auto-deploy when a new image gets built](https://github.com/thechangelog/changelog.com/commit/2d33dbe176bb777a08b866ebaa0928e24bdfe6fa)
- [x] Ensure that all [admin](https://changelog-2022-03-13.fly.dev/admin) tasks - especially uploading mp3s - works as expected
- [x] [Add the new changelog-2022-03-13.fly.dev origin to Fastly](https://manage.fastly.com/configure/services/7gKbcKSKGDyqU7IuDr43eG/diff/103,104)
- [x] Revert https://github.com/thechangelog/changelog.com/pull/407/commits/06f2bbc0f583d9c37d0e83743d79cfce04aaccb9 → https://github.com/thechangelog/changelog.com/pull/407/commits/4af71c5e7ff2f146064a557998b61b40874d01e0
- [x] [Start a new incident](https://app.incident.io/incidents/7)
image

- [x] Perform one last db re-import before production traffic starts getting routed to the new origin
- [x] Route changelog.com production traffic to changelog-2022-03-13.fly.dev origin
- [x] Check Fastly stats & Honeycomb events for any origin issues
- [x] Stop auto-deploys on 22.changelog.com (they trigger LKE db backups) - remove keel
- [x] Delete backup db cron job (this will stop LKE db backups every hour)
- [x] Migrate vanity domains to fly.io
- [x] Capture Fastly VCL working config
- [x] Merge PR
- [x] Update image tag in `fly.toml` to `thechangelog/changelog.com:master`

## How can you help?

* Does the above list sound reasonable?
* Have we missed anything? NOOP if nothing comes to mind.
* Do the code changes look reasonable? → [just one change for now](https://github.com/thechangelog/changelog.com/pull/407/files#diff-8e72c709985cb6a43cc0ab32cb487b8c17d2b2d003338ea42a4e2ad2829979dc)

All Changeloggers & Shippers that are able to help, now is a good time to assemble 🛡
@jerodsanto @adamstac @lawik @akoutmos @mrkurt @chrismccord @brainlid @nickjj 

## What could have gone better?

I will circle back to this, there are a few other important things which I need to cover first.

Just a brain offload for now:

<details>
  <summary><strike><code>fly logs</code> stopped streamings logs for 1' 20" after the app restarted</strike></summary>
  <pre>
2022-03-15T22:41:15Z app[d6b64e8b] iad [info]22:41:15.375 [info] Access ChangelogWeb.Endpoint at https://changelog-2022-03-13.fly.dev
2022-03-15T22:41:15Z app[d6b64e8b] iad [info]22:41:15.893 [info] PromEx.LifecycleAnnotator successfully created start annotation in Grafana.
2022-03-15T22:41:15Z app[d6b64e8b] iad [info]22:41:15.983 [info] PromEx.DashboardUploader successfully uploaded /app/_build/prod/lib/prom_ex/priv/application.json.eex to Grafana.
2022-03-15T22:41:16Z app[d6b64e8b] iad [info]22:41:16.167 [info] PromEx.DashboardUploader successfully uploaded /app/_build/prod/lib/prom_ex/priv/beam.json.eex to Grafana.
2022-03-15T22:41:16Z app[d6b64e8b] iad [info]22:41:16.315 [info] PromEx.DashboardUploader successfully uploaded /app/_build/prod/lib/prom_ex/priv/ecto.json.eex to Grafana.
2022-03-15T22:41:16Z app[d6b64e8b] iad [info]22:41:16.530 [info] PromEx.DashboardUploader successfully uploaded /app/_build/prod/lib/prom_ex/priv/phoenix.json.eex to Grafana.
2022-03-15T22:41:16Z app[d6b64e8b] iad [info]22:41:16.719 [info] PromEx.DashboardUploader successfully uploaded /app/_build/prod/lib/prom_ex/priv/oban.json.eex to Grafana.
2022-03-15T22:41:16Z app[d6b64e8b] iad [info]22:41:16.839 [info] PromEx.DashboardUploader successfully uploaded /app/_build/prod/lib/changelog/priv/grafana_dashboards/app.json to Grafana.
2022-03-15T22:41:16Z app[d6b64e8b] iad [info]22:41:16.983 [info] PromEx.DashboardUploader successfully uploaded /app/_build/prod/lib/changelog/priv/grafana_dashboards/erlang.json to Grafana.
2022-03-15T22:41:17Z app[d6b64e8b] iad [info]22:41:17.118 [info] PromEx.DashboardUploader successfully uploaded /app/_build/prod/lib/changelog/priv/grafana_dashboards/ecto.json to Grafana.
2022-03-15T22:41:17Z app[d6b64e8b] iad [info]22:41:17.253 [info] PromEx.DashboardUploader successfully uploaded /app/_build/prod/lib/changelog/priv/grafana_dashboards/phoenix.json to Grafana.
2022-03-15T22:41:17Z app[d6b64e8b] iad [info]22:41:17.907 [error] Handler {TelemetryMetricsPrometheus.Core.EventHandler, #PID<0.531.0>,
2022-03-15T22:41:17Z app[d6b64e8b] iad [info] [:changelog, :prom_ex, :oban, :init, :circuit, :backoff, :milliseconds]} has failed and has been detached. Class=:error
2022-03-15T22:41:17Z app[d6b64e8b] iad [info]Reason={:badkey, :circuit_backoff,
2022-03-15T22:41:17Z app[d6b64e8b] iad [info] %Oban.Config{
2022-03-15T22:41:17Z app[d6b64e8b] iad [info]   dispatch_cooldown: 5,
2022-03-15T22:41:17Z app[d6b64e8b] iad [info]   engine: Oban.Queue.BasicEngine,
2022-03-15T22:41:17Z app[d6b64e8b] iad [info]   get_dynamic_repo: nil,
2022-03-15T22:41:17Z app[d6b64e8b] iad [info]   log: false,
2022-03-15T22:41:17Z app[d6b64e8b] iad [info]   name: Oban,
2022-03-15T22:42:37Z app[d6b64e8b] iad [info]22:42:37.080 request_id=FtyvKaNewnaiVAUAABEB [info] GET /manifest.json
2022-03-15T22:42:37Z app[d6b64e8b] iad [info]22:42:37.080 request_id=FtyvKaNewnaiVAUAABEB [info] Sent 200 in 732µs
  </pre>
</details>

~~With my [CF loggregator](https://github.com/cloudfoundry/loggregator-release) & [Heroku Logplex](https://devcenter.heroku.com/articles/logplex) experience, I am pretty sure that when our app boots, we stream too many logs and the overload protection mechanism gets triggered. This sheds a bunch of logs with the `2022-03-15T22:41:17Z` timestamp and unfortunately, these are exactly the logs which we need to debug an error. I will check to see if this crash gets logged in Sentry - it should! Nope, we don't 😑~~

### CODE REVIEW

**Comment by lawik** [comment]
This is fun. Hope the journey goes smoothly :)
I have a client project on fly right now and haven't had much in the way of problems.
Running postgres cli commands against my db over wireguard was a bit finicky but once I'd gotten it to work it worked well. For one thing I had to match the cli tools version locally so ended up turning to docker for that.

**Comment by gerhard** [comment]
> This is fun. Hope the journey goes smoothly :)

I'm glad that you are enjoying it!

We have hit a couple of issues, but nothing that we couldn't work around. I will capture them to the above description as we get closer to wrapping it up.

The big issue that is currently blocking progress is admin logins not working. There are no errors in the app log, but it still doesn't work. The issue that I am referring to is:

- Figure out why we cannot login as admins via email → this feels like a @jerodsanto task, and he already has the context. I am assuming that Jerod will need to set fly CLI up so that he can interact with the new infra, but I am waiting for him to pull my leg 😀
```
2022-03-15T23:48:36Z app[85c3240d] iad [info]23:48:36.025 request_id=Ftyyw2bsYSdbQdkAACfi [info] GET /in/67657268617264406368616E67656C6F672E636F6D7C30363945313631313432333137363639
2022-03-15T23:48:36Z app[85c3240d] iad [info]23:48:36.074 request_id=Ftyyw2bsYSdbQdkAACfi [info] Sent 302 in 48ms
2022-03-15T23:48:36Z app[85c3240d] iad [info]23:48:36.164 request_id=Ftyyw28rpuBF5-YAACgi [info] GET /~
2022-03-15T23:48:36Z app[85c3240d] iad [info]23:48:36.170 request_id=Ftyyw28rpuBF5-YAACgi [info] Sent 302 in 6ms
2022-03-15T23:48:36Z app[85c3240d] iad [info]23:48:36.256 request_id=Ftyyw3SvY3s2S4YAAChC [info] GET /in
2022-03-15T23:48:36Z app[85c3240d] iad [info]23:48:36.260 request_id=Ftyyw3SvY3s2S4YAAChC [info] Sent 200 in 3ms
```

> I have a client project on fly right now and haven't had much in the way of problems. Running postgres cli commands against my db over wireguard was a bit finicky but once I'd gotten it to work it worked well.

```
flyctl proxy 5432 -a postgres-2022-03-12
psql -h 127.0.0.1 changelog postgres
```

This worked well for me from a developer experience (DX) perspective, but the speed was dog slow. Importing the db was at least 2x slower over wireguard than when I was running it directly in our K8s cluster. I didn't spend too much time on it since we are talking 5 minutes slower, but it was something that made me 🤔

> For one thing I had to match the cli tools version locally so ended up turning to docker for that.

I know exactly what you mean. That is the higher bit perspective that I hold in this migration: how do we capture all these tasks in a Dagger plan which anyone is able to use on their host, without polluting their environment? Fun times ahead indeed 😉

**Comment by gerhard** [comment]
There is something for you here @icecrime ;)

Notice above how the label which I have added initially - `echoes/intent: upgrade` - was removed by the **echoes-hq** bot.

It took me a while to figure out that this was due to this outcome not existing in https://app.echoeshq.com/settings/outcomes

image

It would have helped for the bot to drop a message why it removed the label. Anything that would have connected the dots quicker is a step in the right direction.

---
As a side-note, I enjoyed your perspectives in the [Kubernetes documentary](https://www.youtube.com/watch?v=BE77h7dmoQU&t=228s). You will want to tune into [Ship It](https://changelog.com/shipit) episode 44 when it comes out later this week 😉

**Comment by mrkurt** [comment]
> This worked well for me from a developer experience (DX) perspective, but the speed was dog slow. Importing the db was at least 2x slower over wireguard than when I was running it directly in our K8s cluster. I didn't spend too much time on it since we are talking 5 minutes slower, but it was something that made me 🤔

A 2x slowdown is somewhat normal for big operations over `fly proxy`. This is using user mode wireguard, it's not nearly as fast as what's in the Linux kernel.

We have a migrator project you can use to run imports from a Fly VM to another Fly VM. It will be much faster: https://github.com/fly-apps/postgres-migrator

You can also run `fly ssh console -a <database>` and do the dumb + import "locally".

**Comment by gerhard** [comment]
Any idea @icecrime why the **echoes-hq** bot keeps removing the labels, and making the check fail? I thought that [I understood it earlier](https://github.com/thechangelog/changelog.com/pull/407#issuecomment-1068918133), but now I am not sure 🤔

image

**Comment by gerhard** [comment]
When we configured Fastly to route all production traffic from Fastly ([changelog.com](https://changelog.com)) to Fly ([changelog-2022-03-13.fly.dev](https://changelog-2022-03-13.fly.dev)), Fastly was sending this traffic to our S3 bucket origin instead 🤦‍♂️

This was wrong, since only `cdn.changelog.com` requests should be sent to the S3 bucket. The condition was right there, and yet... it was not working as expected.

I thought that we had something misconfigured, but clicking through the Fastly service config UI is just pants, so I downloaded the VCL config and then 😲

```
$ wc -l fastly-changelog-v113.vcl
   12970 fastly-changelog-v113.vcl
```

There are nearly ~13k lines of VCL config, out of which ~12.3k are just shielding config 🤔

Having trimmed all that excess, we were left with ~700 lines of relevant VCL config:

```
$ wc -l fastly-changelog-v113.no-shielding.vcl
     718 fastly-changelog-v113.no-shielding.vcl
```

Even so, we couldn't find the problem. Everything looked right, and yet `changelog.com` requests were not getting sent to the correct backend. Maybe I was getting too tired and I just couldn't see the problem even if my life depended on it...

We scrambled to finish setting up another LKE instance and route all changelog.com traffic to the new LKE origin, [22.changelog.com](https://22.changelog.com), and call it a long, 16h day.

I was now able to make some headspace, start with a clean slate, and confirm that Fastly → Fly integration works as expected: https://lazu.ch/

image

> NOTE: as dope as that `h3` protocol is, let's focus on the fact that this works as expected 😎

And it works directly too: https://old-flower-9005.fly.dev/

image

So there is something wrong with the [`2022.fly/lazu.ch/fastly-changelog-v113.no-shielding.vcl`](https://github.com/thechangelog/changelog.com/pull/407/files#diff-e62f40365e19e255243ba4725b99b75c8d3b21bc867675c3fc8e3302e3e1c96c) config, and we are going to find out what next. Before we can do that, there is something else that we need to do first:

- [ ] Configure the managed PostgreSQL instance to get backed up periodically (every 1h)
- [ ] Backup the managed PostgreSQL instance on every deploy
- [ ] Reload managed PostgreSQL instance with latest backup
- [ ] Configure the LKE 1.22 app instance to use the managed PostgreSQL instance

The reason why we need to do this first is because we want a single db instance serving both the LKE 1.22 & Fly app instances. Regardless what happens with the experiments, db data will remain consistent and we won't have to worry about missed writes. Currently LKE 1.22 app instance uses a local db, and the Fly app instance uses the managed PostgreSQL instance.

In hindsight, we should have split this issue into multiple PRs, and that should have been the first PR to get merged. Things got hectic with the LKE 1.20 migration, so I am not surprised that this did not go as smoothly as it could, but now that we had more time to think about it, the incremental steps are obvious.

**Comment by gerhard** [comment]
This confirms that https://fly.changelog.com (Fastly) is proxying correctly to https://changelog-2022-03-13.fly.dev/ (Fly).

FTR: https://manage.fastly.com/configure/services/7gKbcKSKGDyqU7IuDr43eG/diff/113,114

**Comment by gerhard** [comment]
Now that we have LKE -> fly.io, [Miss Lantecy in Fastly](https://manage.fastly.com/stats/historic/services/7gKbcKSKGDyqU7IuDr43eG/in/all/from/1649026980000/to/1649113380000/by/minute) was interesting to notice:

image

I suspect that [this related Honeycomb.io query](https://ui.honeycomb.io/changelog/datasets/fastly/result/wRPAdrbjkyE) will come in handy to continue exploring:

image

**Comment by gerhard** [comment]
Reminder to investigate Fastly cache errors (convert to issue).

[Honeycomb starting point](https://ui.honeycomb.io/changelog/datasets/fastly/result/s9AjNR5UWv9):

image

**Comment by gerhard** [comment]
https://github.com/thechangelog/changelog.com/actions/runs/2093282873

image

**Pull request merged**
