### PR TITLE
Podcast page tabs

### PR DESCRIPTION
**Pull request by codyjames**

### CODE REVIEW

**Comment by jerodsanto** [comment]
@codyjames @adamstac upcoming looks pretty lame in its current form. I suggest maybe we just comment it out and ship the Recommended tab first.

2018-05-02 at 10 05 am

Also do we have an empty state ready for these views?

**Comment by adamstac** [comment]
For the content line in upcoming we could print `Recording scheduled for 2pm CT on Apr 25, 2018` or something like that to fill it out and not make it so lame.

Also, we def should have an empty state for this. Could be similar to the plain text sentence used on retired shows.

**Comment by jerodsanto** [comment]
(Worth noting that Cody had the record time in there and I yoinked it. Down with including it, but it also looked a bit lame in its current form.)

**Comment by adamstac** [comment]
We can pull it and get a specific design in place for scheduled episodes we can all agree on.

**Pull request merged**
