### PR TITLE
Fix elixir link in readme

### PR DESCRIPTION
**Pull request by michaeljdennis**

### CODE REVIEW

**Comment by jerodsanto** [comment]
💚 💚 💚

**Comment by michaeljdennis** [comment]
Looks like the blog post has the same broken link. https://changelog.com/posts/changelog-is-open-source

**Comment by jerodsanto** [comment]
Fix there too now, thanks again for pointing it out!

**Comment by michaeljdennis** [comment]
No problem. Glad to help!

**Pull request merged**
