### PR TITLE
Support faster playback

### LINKED ISSUE #139: Allow faster playback
Let us play the audio at 1.25x or 1.5x speed! I can help out with this in a PR if it sounds good, but I don't know where to fit it in the player.

### PR DESCRIPTION
**Pull request by sotojuan**
Adds a keyboard shortcut ("s") that toggles playback speed.

Each keypress speeds up the audio by 0.5x, wrapping back to 1x when the
speed is 2x.

Closes #139.

### CODE REVIEW

**Comment by jerodsanto** [comment]
💚 I hope to take a look at this over the weekend!

**Comment by jerodsanto** [comment]
@sotojuan this looks good! Nice and simple :) 

It looks like you accidentally committed the uploaded episode you were testing with. Pull that out and then we'll :shipit:

**Comment by sotojuan** [comment]
Done!

**Comment by jerodsanto** [comment]
🎉🎉🎉 thanks so much for contributing this! 💚

**Pull request merged**
