### PR TITLE
replace npm with yarn to install dependencies. Ref #131

### PR DESCRIPTION
**Pull request by soleo**
Ref to #131 

Install dependencies via yarn instead of npm

### CODE REVIEW

**Comment by jerodsanto** [comment]
I'm 👍 on this because I'm 👍 on lock files. 

However, I think this might complicate our infrastructure setup since our production instances don't have yarn on them at the moment (and don't use the setup script like devs do). @gerhard your thoughts?

**Comment by gerhard** [comment]
[I like what YARN brings to the table[(https://medium.com/@nikjohn/facebooks-yarn-vs-npm-is-yarn-really-better-1890b3ea6515#.v9xfe8iyw), happy to merge.

**Comment by soleo** [comment]
I think it would have a minimum impact both on dev and production environment. In the production site, you can still use the npm, it uses the same package.json file to look for independencies. If you don't want to replace it with yarn, it would still work. Yarn is faster though. I would consider use it for both dev and live environment.

**Comment by jerodsanto** [comment]
Works for me, thanks @soleo @gerhard! :green_heart::green_heart::green_heart:

**Pull request merged**
