### PR TITLE
Cleanup assets

### PR DESCRIPTION
**Pull request by codyjames**

### CODE REVIEW

**Comment by codyjames** [comment]
@jerodsanto Think we could build a script to loop through images in the static folder and check to see if they are referenced in either `assets/app` or `lib/changelog_web/templatse`?

**Comment by jerodsanto** [comment]
@codyjames added one, run in the root directory `./script/assets_unused`

It assumes you have `ack` installed (brew install ack if you don't). Definitely give the output a critical eye as we may be constructing filename strings from podcast slugs, etc in places.

**Comment by codyjames** [comment]
@jerodsanto This is great! Thanks!

**Comment by gerhard** [comment]
@codyjames 🚢 ?

**Comment by codyjames** [comment]
- [ ] assets/static/apple-touch-icon.png not referenced
- [ ] assets/static/fonts/Menlo-Regular.svg not referenced
- [ ] assets/static/images/brand/changelog-mark-only-white.svg not referenced
- [ ] assets/static/images/brand/logo-changelog-white.svg not referenced
- [ ] assets/static/images/brand/logo-changelog.svg not referenced
- [ ] assets/static/images/brand/logo-films-white.svg not referenced
- [ ] assets/static/images/brand/logo-films-wide-white.svg not referenced
- [ ] assets/static/images/brand/logo-news-white.svg not referenced
- [ ] assets/static/images/brand/logo-news-wide-white.svg not referenced
- [ ] assets/static/images/brand/logo-podcasts-white.svg not referenced
- [ ] assets/static/images/content/about/adam.jpg not referenced
- [ ] assets/static/images/content/about/heather.jpg not referenced
- [ ] assets/static/images/content/about/jerod.jpg not referenced
- [ ] assets/static/images/content/community/sponsors/sponsor-gosquared.png not referenced
- [ ] assets/static/images/content/community/sponsors/sponsor-oscon.png not referenced
- [ ] assets/static/images/content/community/sponsors/sponsor-stackimpact.png not referenced
- [ ] assets/static/images/content/sponsors/datadog-gray@2x.png not referenced
- [ ] assets/static/images/content/sponsors/datadog@2x.png not referenced
- [ ] assets/static/images/content/sponsors/facebook-gray@2x.png not referenced
- [ ] assets/static/images/content/sponsors/fastly@2x.png not referenced
- [ ] assets/static/images/content/sponsors/google-gray@2x.png not referenced
- [ ] assets/static/images/content/sponsors/ibm-gray@2x.png not referenced
- [ ] assets/static/images/content/sponsors/indeed.png not referenced
- [ ] assets/static/images/content/sponsors/indeed@2x.png not referenced
- [ ] assets/static/images/content/sponsors/intel-dark.png not referenced
- [ ] assets/static/images/content/sponsors/intel-dark@2x.png not referenced
- [ ] assets/static/images/content/sponsors/intel-favicon.png not referenced
- [ ] assets/static/images/content/sponsors/intel-grey@2x.png not referenced
- [ ] assets/static/images/content/sponsors/intel.png not referenced
- [ ] assets/static/images/content/sponsors/intel@2x.png not referenced
- [ ] assets/static/images/content/sponsors/leo-schramm.jpg not referenced
- [ ] assets/static/images/content/sponsors/linode@2x.png not referenced
- [ ] assets/static/images/content/sponsors/linux-foundation-gray@2x.png not referenced
- [ ] assets/static/images/content/sponsors/microsoft-gray@2x.png not referenced
- [ ] assets/static/images/content/sponsors/paypal-gray@2x.png not referenced
- [ ] assets/static/images/content/sponsors/rollbar-dark.png not referenced
- [ ] assets/static/images/content/sponsors/rollbar-dark@2x.png not referenced
- [ ] assets/static/images/content/sponsors/rollbar-favicon.png not referenced
- [ ] assets/static/images/content/sponsors/rollbar@2x.png not referenced
- [ ] assets/static/images/content/sponsors/slack-gray@2x.png not referenced
- [ ] assets/static/images/content/sponsors/uber-gray@2x.png not referenced
- [ ] assets/static/images/defaults/type-announcement.png not referenced
- [ ] assets/static/images/defaults/type-audio.png not referenced
- [ ] assets/static/images/defaults/type-link.png not referenced
- [ ] assets/static/images/defaults/type-project.png not referenced
- [ ] assets/static/images/defaults/type-video.png not referenced
- [ ] assets/static/images/icons/form-processing.svg not referenced
- [ ] assets/static/images/icons/form-select-arrow.svg not referenced
- [ ] assets/static/images/icons/form-success.svg not referenced
- [ ] assets/static/images/icons/icon-date.svg not referenced
- [ ] assets/static/images/icons/icon-details-grey.svg not referenced
- [ ] assets/static/images/icons/icon-details-white.svg not referenced
- [ ] assets/static/images/icons/icon-details.svg not referenced
- [ ] assets/static/images/icons/icon-download-grey.svg not referenced
- [ ] assets/static/images/icons/icon-download-white.svg not referenced
- [ ] assets/static/images/icons/icon-link-grey.svg not referenced
- [ ] assets/static/images/icons/icon-link.svg not referenced
- [ ] assets/static/images/icons/icon-location.svg not referenced
- [ ] assets/static/images/icons/icon-play-grey.svg not referenced
- [ ] assets/static/images/icons/icon-search.svg not referenced
- [ ] assets/static/images/icons/icon-share-grey.svg not referenced
- [ ] assets/static/images/icons/icon-share-white.svg not referenced
- [ ] assets/static/images/icons/icon-sponsor-white.svg not referenced
- [ ] assets/static/images/icons/icon-subscribe-white.svg not referenced
- [ ] assets/static/images/icons/icon-tag-white.svg not referenced
- [ ] assets/static/images/icons/icon-tag.svg not referenced
- [ ] assets/static/images/icons/icon-timestamp.svg not referenced
- [ ] assets/static/images/icons/podcast-link.svg not referenced
- [ ] assets/static/images/podcasts/master-cover-art.png not referenced
- [ ] assets/static/images/podcasts/master-medium.png not referenced
- [ ] assets/static/images/podcasts/master-original.png not referenced
- [ ] assets/static/images/podcasts/master-small.png not referenced
- [ ] assets/static/images/podcasts/polyglot-abstract-art.svg not referenced
- [ ] assets/static/images/share/gotime-fb.png not referenced
- [ ] assets/static/images/share/gotime-twitter.png not referenced
- [ ] assets/static/images/share/master-fb.png not referenced
- [ ] assets/static/images/share/master-twitter.png not referenced
- [ ] assets/static/images/share/podcast-fb.png not referenced
- [ ] assets/static/images/share/podcast-twitter.png not referenced
- [ ] assets/static/images/share/rfc-fb.png not referenced
- [ ] assets/static/images/share/rfc-twitter.png not referenced
- [ ] assets/static/images/share/sitewide-fb.png not referenced
- [ ] assets/static/images/share/sitewide-twitter-large.png not referenced
- [ ] assets/static/mstile-144x144.png not referenced
- [ ] assets/static/mstile-310x150.png not referenced
- [ ] assets/static/mstile-310x310.png not referenced
- [ ] assets/static/mstile-70x70.png not referenced
- [ ] assets/static/safari-pinned-tab.svg not referenced

**Comment by codyjames** [comment]
@jerodsanto I think this is good! Anything in that last comment that is unchecked is either something that I think is being used or something that I don't think we should delete just yet (only a few of those though).

I renamed the assets/assets folder to assets/static. Not sure if there are bigger implications to that but you may want to make sure it works on production.

**Comment by gerhard** [comment]
🚀

**Pull request merged**
