### PR TITLE
Move assets to S3

### PR DESCRIPTION
**Pull request by jerodsanto**
We are moving all file uploads and static assets out of `priv/static` and on to S3. This branch includes all chages necessary to make that transition and shouldn't be merged until it's been tested in a production sandbox.

New environment variables:

- `AWS_REGION` - likely `us-east-1`
- `AWS_ASSETS_BUCKET` - tells Waffle where to upload files
- `AWS_UPLOADS_HOST` - tells Waffle which host to use for generating uploaded file URLs

_(I tried using separate AWS credentials for UPLOADS vs STATS, but because Waffle uses ExAws like our stats analyzer does, this became troublesome.)_

Things we still need:

- [x] A process to mirror/sync current uploads to the production S3 bucket
- [ ] A `cdn.changelog.com` origin in Fastly that points to the production S3 bucket
- [x] A build step that takes compiled assets and uploads them to S3 on deploy

### CODE REVIEW

**Comment by gerhard** [comment]
This app instance is now running at https://22.changelog.com

It is failing to boot with the following warning:

```
01:51:52.960 [info] Uploading images/content/sponsors/microsoft-gray@2x-d8e696291856a9d46f203ff9640e9f6e.png
01:51:52.965 [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/static/images/content/sponsors/microsoft-gray%402x-d8e696291856a9d46f203ff9640e9f6e.png" ATTEMPT: 1
01:51:52.975 [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/static/images/content/sponsors/microsoft-gray%402x-d8e696291856a9d46f203ff9640e9f6e.png" ATTEMPT: 2
01:51:52.986 [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/static/images/content/sponsors/microsoft-gray%402x-d8e696291856a9d46f203ff9640e9f6e.png" ATTEMPT: 3
01:51:52.991 [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/static/images/content/sponsors/microsoft-gray%402x-d8e696291856a9d46f203ff9640e9f6e.png" ATTEMPT: 4
01:51:53.054 [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/static/images/content/sponsors/microsoft-gray%402x-d8e696291856a9d46f203ff9640e9f6e.png" ATTEMPT: 5
01:51:53.362 [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/static/images/content/sponsors/microsoft-gray%402x-d8e696291856a9d46f203ff9640e9f6e.png" ATTEMPT: 6
01:51:53.546 [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/static/images/content/sponsors/microsoft-gray%402x-d8e696291856a9d46f203ff9640e9f6e.png" ATTEMPT: 7
01:51:53.994 [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/static/images/content/sponsors/microsoft-gray%402x-d8e696291856a9d46f203ff9640e9f6e.png" ATTEMPT: 8
01:51:56.070 [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/static/images/content/sponsors/microsoft-gray%402x-d8e696291856a9d46f203ff9640e9f6e.png" ATTEMPT: 9
01:52:00.747 [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/static/images/content/sponsors/microsoft-gray%402x-d8e696291856a9d46f203ff9640e9f6e.png" ATTEMPT: 10
```

I am dropping the `changelog.static.upload` task from the boot command until we can fix this.

**Comment by jerodsanto** [comment]
@gerhard we need to define all of the AWS related environment variables (see my first comment on this PR) in order for the `changelog.static.upload` mix task to do its thing. You can see in the logs that those `https:/static/...` paths are missing the appropriate domain section of the URL. How do we define environment variables in the new setup?

**Comment by gerhard** [comment]
> @gerhard we need to define all of the AWS related environment variables (see my first comment on this PR) in order for the `changelog.static.upload` mix task to do its thing.

Got it!

> How do we define environment variables in the new setup?

This is where & how secret environment variables are declared: https://github.com/thechangelog/changelog.com/blob/4c7d470f76ef359e6640dd3cceb861e52ef63076/2022/manifests/changelog/app.yml#L143-L147

And this is an example of a regular, non-secret variable: https://github.com/thechangelog/changelog.com/blob/4c7d470f76ef359e6640dd3cceb861e52ef63076/2022/manifests/changelog/app.yml#L173-L174

I think it would be more effective if we paired-up on this one.

**Review by lawik — COMMENTED** [review]
I haven't seen this before myself. I typically run a compiled release rather than the mix project.

I didn't see anything in Mox about terminating the do statement at the surface level. Top of mind was if it was looking for some particular return value. Doesn't seem like it.

I wonder if your script triggers an exit somewhere. 

No errors or anything?

**Comment by jerodsanto** [comment]
Currently thinking our task running `Mix.Task.run("app.start")` makes it so mix thinks `phx.server` has already been run prior...

**Comment by gerhard** [comment]
> I typically run a compiled release rather than the mix project.

That is **top of my mind** for when we get to work together again. Let's find a time to push this forward: https://github.com/thechangelog/changelog.com/discussions/402

> I wonder if your script triggers an exit somewhere.
> No errors or anything?

Nope, nothing, everything works as expected and exits `0` when we run it on its own, i.e. `mix changelog.static.upload`.

> Currently thinking our task running `Mix.Task.run("app.start")` makes it so mix thinks `phx.server` has already been run prior...

@jerodsanto may be onto something...

**Comment by gerhard** [comment]
Prepare to migrate:
- clean up `2022/manifests/changelog/app.yml`

Steps to migrate prod to LKE 22:
- Change `STATIC_URL_HOST` to cdn.changelog.com in `2022/manifests/changelog/app.yml`
- Change `URL_HOST` to changelog.com in `2022/manifests/changelog/app.yml`
- Enable all secrets in `2022/manifests/changelog/app.yml`
- Trigger database backup on prod
- Sync S3 uploads folder
- Delete 22 db & re-create <- @jerodsanto knows how to do this
- In Fastly replace cdn22.changelog.com with cdn.changelog.com
- In Fastly replace existing origin with 22.changelog.com
  - Remember to update the health check
- Apply new service version config
- Change `EXTERNAL_DNS_POLICY` to `sync`
- Uncomment `EXTERNAL_DNS_TXT_OWNER_ID`
- Uncomment `2022/manifests/changelog/dns.yml` & apply

**Review by gerhard — APPROVED** [review]
Let's ship it!

**Comment by gerhard** [comment]
You can hear the background to this in [Ship It! #40 - Kaizen! New beginnings](https://changelog.com/shipit/40) 👈🏻 link goes live Feb 18, 2022

**Pull request merged**
