### PR TITLE
Add OS X dark mode support [WIP]

### PR DESCRIPTION
**Pull request by MarkReeder**
This is a work in progress, but I wanted to validate a few assumptions before going too much further.
Here are a couple of screenshots of the current News page status:
screen shot 2018-10-27 at 1 09 55 am
screen shot 2018-10-27 at 1 10 08 am

Biggest changes are:
- re-working of the sponsor images to use svg instead of png, primarily to make it easier to swap images based on media queries, using `picture` / `srcset`
- extraction of header dark styles into a `@mixin` so they could be more easily used in the existing manner as well as with the `prefers-color-scheme: dark` media query
- the addition of a couple new colors
- new svg images to support the changes
- the new dark styles

The main things I wanted to validate before going too much further are:
- the organization of the dark mode media queries
- the image changes (from png -> svg and the social icon color)

### CODE REVIEW

**Comment by codyjames** [comment]
@MarkReeder Great stuff here! I just got back from Japan and will look this over and compile my thoughts early this week.

**Comment by MarkReeder** [comment]
Any updates here @codyjames ? Also, @jerodsanto you mentioned in Slack about getting a sanitized dB snapshot which I'd need to finish out the News page styling.

**Comment by codyjames** [comment]
@MarkReeder Sorry for the delay! My current thinking is that the Dark Mode support should be limited to "news" pages for now. So, the Homepage as well as News items ([example](https://changelog.com/news/guessjs-a-toolkit-for-enabling-datadriven-userexperiences-on-the-web-j46g)) would get a Dark Mode. Perhaps "Podcast" pages would also get a Dark Mode.

However, informational pages (such as [Community](https://changelog.com/community)) should not get a Dark Mode.

This should make Dark Mode enthusiasts happy without drastically affecting our development time/complexity.

Regarding your changes so far: I think they all work for me except the footer sponsor logos. I'd like to keep those as-is. So, perhaps the very bottom "Sponsor" section of the footer can keep having a white background?

Let me know what you think.
Thanks!

**Comment by MarkReeder** [comment]
No worries on the delay- I've been pretty busy recently too.

Happy to change the footer sponsor logos back- would you prefer white blocks around them or a fully white section for them?

Also, are you opposed to svg footer images in general, or just the dark mode images? The svg versions are smaller and scale better for high resolution screens. The only downside I see is some potential browser compatibility issues, but they're well supported across almost everything that's in use today: https://caniuse.com/#feat=svg

The other thing I'll need is a sanitized dB snapshot, or some dummy data/guidance on seeding some dummy data.

**Comment by codyjames** [comment]
@MarkReeder I think just have that BG be white for that last section in the footer.

Not opposed to SVG. If @adamstac is fine with SVG for sponsor logos, I'm fine with it as well. Mostly it'd depend on what we typically have available and how hard it is to track SVG versions down.

@jerodsanto Any idea on how we could provide dummy data?

**Comment by MarkReeder** [comment]
Sounds great- thanks for the clarifications. I tracked down and added svg logos for all current sponsors. Seems reasonable to default to svg and fall back to png if svg is unavailable from a potential future sponsor. As soon as I get the dummy data and some free time, I'll update.

**Comment by bennypowers** [comment]
My eyes! It burns! Can we get this pr up to date with `prefers-color-scheme`?

**Comment by gerhard** [comment]
Still LGTM! This is what I'm currently thinking: https://github.com/thechangelog/changelog.com/issues/376#issuecomment-1224979419

**Comment by gerhard** [comment]
Closing because https://github.com/thechangelog/changelog.com/issues/376#issuecomment-1232098748

**Pull request closed without merging**
