### PR TITLE
Deploy PgHero & connect to Neon.tech Postgres

### PR DESCRIPTION
**Pull request by gerhard**
- Provides insights into our Neon.tech Postgres setup
- Available on our 6PN network as <http://pghero-2024-03-27.internal:8080>
image

While at it, I've also bumped all utilities to latest (except Elixir - #493)

---

Follow-up to:
- https://github.com/thechangelog/changelog.com/pull/492

### CODE REVIEW

**Review by jerodsanto — APPROVED** [review]
Excited to try it

**Comment by gerhard** [comment]
After this got merged, we started seeing 503s like this one:
image

[More details:](https://ui.honeycomb.io/changelog/datasets/fastly/result/u87WCxPsrSY)
image

If these do not go away after we merge #508, where Erlang is downgraded to v26.2.2, I porpose that we go back to v26.2. WDYT @jerodsanto?

**Comment by gerhard** [comment]
Interestingly, [Fly.io metrics is not showing any issues for the app, apart for some elevated 404s following the deploy](https://fly-metrics.net/d/fly-app/fly-app?from=1711719124971&orgId=23559&to=1711727436971&var-app=changelog-2024-01-12&viewPanel=3)

image

---
[App response latency seems unchanged](https://fly-metrics.net/d/fly-app/fly-app?from=now-3h&to=now&var-app=changelog-2024-01-12&orgId=23559&viewPanel=13)

image

**Comment by gerhard** [comment]
Going back to Erlang v26.2.2 part of #508 [seems to have fixed those `503s`](https://ui.honeycomb.io/changelog/datasets/fastly/result/yWq2ohwu6A9):

image

**Pull request merged**
