### PR TITLE
Playbar now matches player state

### PR DESCRIPTION
**Pull request by FrancosLab**
Found Thechangelog podcast today and listened to multiple casts today gotta say I was really vibing with it. Although while using the site I kept running into an issue where I kept hitting the play button on the playbar instead of the bottom player which auto restarted any podcast instead of resuming it if it was paused, super annoying when you have no idea what timestamp you were on during a 2 hour podcast.

With this pull request the play bars are now in sync with the bottom player and properly play and pause <3

ps. shout out to Guillermo Rauch. 

Before: 

After: (sorry for external link gif to big to upload on here)

https://gfycat.com/InstructiveImpossibleHalibut

### CODE REVIEW

**Comment by jerodsanto** [comment]
@FrancosLab glad you found us! 😄

This is a really cool feature. I hope to give it a closer look before the week's out. 💚

**Comment by FrancosLab** [comment]
Just pinging this :) 

If you need me to change anything I'm more than willing too!

**Comment by jerodsanto** [comment]
@FrancosLab I'm keen on getting this in, it's just fallen down the priority list a bit. Hang tight!

**Comment by jerodsanto** [comment]
:green_heart: :green_heart: :green_heart:

**Pull request merged**
