### PR TITLE
Transcripts

### PR DESCRIPTION
**Pull request by jerodsanto**

### CODE REVIEW

**Comment by jerodsanto** [comment]
I believe this is all ready for you @codyjames! Holler if you have questions/needs ✊

**Comment by codyjames** [comment]
Some initial experimentation: https://www.figma.com/file/YoEBMqtDkM9tFS2egfTNYbX4/Changelog-3.0

Trying out Figma due to it being cheaper than Sketch+Abstract.

**Comment by jerodsanto** [comment]
Adam and I like the top one! Let's go that direction 👌

**Comment by codyjames** [comment]
@jerodsanto Give that a whirl. There are some bracket issues (looks weird around timestamps) and some markdown parser issues (/podcast/256#transcript-230) but it's mostly there.

**Comment by jerodsanto** [comment]
@codyjames looking pretty good to me! We need a button/CTA to edit/improve the transcript which links to source on GitHub. Other than that (and the brackets thing you mentioned), I think it's ready to go.

_(I do not see the markdown parser issues you referenced in podcast/256. Can you show me what you're talking about?))

**Comment by codyjames** [comment]
The markdown parser seems to be parsing the number "270" as an <ol>.

**Pull request merged**
