### PR TITLE
Experiment with Dagger for core CI/CD

### PR DESCRIPTION
**Pull request by gerhard**
- [x] Capture `deps`, `test` & `assets` in Dagger
- [x] Build & publish prod container image to DockerHub
- [x] Run it in a GitHub Actions - [Tailscale integration](https://tailscale.com/blog/2021-05-github-actions-and-tailscale/) + [github-action](https://github.com/tailscale/github-action)
- [x] Switch to dagger `>v0.1.0-alpha.30` in GitHub Actions
- [x] Download dagger from dl.dagger.io in `make dagger-ci` so that others can run this target
- [x] Set prod_image build vars as inputs in GitHub Actions
- [x] Clean commit history & remember to drop the Linux `dagger` binary commits
- [x] Only tag when running on primary branch
- [x] Rebase
- [ ] Post-merge: add screenshot to compare CircleCI vs GitHub Actions + Dagger
- [ ] Post-merge: update prod app to use the `:dagger` tag 😎 (a.k.a. Ship It!)

## Why are you doing this?
To reduce the time it takes to deploy code into production - _5 minutes or bust_ - and make the migration from CircleCI to GitHub Actions as easy as possible. While the current pipeline **appears** to take less than 5 minutes, it used to take 8-10 minutes when we started with this experiment, and the time that jobs wait in the queue is not shown. Being able to migrate between CI systems easily, and run the exact thing that CI runs locally are huge benefits. Also remember that this is a pre-release version of Dagger, future versions are only likely to improve on the speed: _Make it work - that's this PR. Make it right - next year. Make it fast - I think next year too._

Current pipeline:
image

## What does the new pipeline look like from a high-level perspective?

```
                 app
                 |
                 v
test_db_start    deps ----------------------------------------\
|                |                      |                     |
|                v                      v                     v
|                deps_compile_test      deps_compile_prod     assets_compile
|                |                      |               |     |
|                |                      |               \-----|
|                v                      v                     |
\--------------> test                   image_prod_cache      assets_digest
                 |                      |                     |
test_db_stop <---|                      v                     |
                 |                      image_prod <----------/
                 |                      |
                 |                      v
                 \--------------------> image_prod_tag
```

## What makes the new pipeline better?

The same pipeline run as above is a ~2m quicker with Dagger, or a 2.23x improvement:
image

And this will run the same against any Docker daemon - including a local Docker - so no special CI setup required 🤘🏻

OpenTracing is built-in 😎
image

## What does the GitHub Actions integration look like?

image

Eyeballing the checks, this new approach is ~2x quicker than `build` which runs in CircleCI (1m vs 2m) and ~4x quicker than the initial GitHub Actions `mix test` implementation (1m vs 4m).
image

And because the entire CI implementation is kept in Dagger, the GitHub Action definition is simple and therefore portable. In other words, I can imagine the CircleCI equivalent being just as straightforward:
```yaml
name: Prod image

on:
  push:
    branches:
  workflow_dispatch:

env:
  DOCKER_HOST: "tcp://100.113.182.91:2375"
  OTEL_EXPORTER_JAEGER_ENDPOINT: "http://100.113.182.91:14268/api/traces"

jobs:
  build_test_ship:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code...
        uses: actions/checkout@v2

      - name: Install Dagger...
        uses: dagger/dagger-action@v1
        with:
          # ⚠️  Keep this in sync with 2021/dagger.mk
          version: 0.1.0-alpha.31
          age-key: ${{ secrets.DAGGER_AGE_KEY }}
          args: version

      - name: Configure Tailscale tunnel for remote Docker Engine...
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Run prod_image environment with Dagger on remote Docker Engine...
        run: |
          /opt/hostedtoolcache/dagger/*/x64/dagger input text docker_host "$DOCKER_HOST" --environment prod_image
          /opt/hostedtoolcache/dagger/*/x64/dagger input text git_branch "$GITHUB_REF_NAME" --environment prod_image
          /opt/hostedtoolcache/dagger/*/x64/dagger input text git_sha "$GITHUB_SHA" --environment prod_image
          /opt/hostedtoolcache/dagger/*/x64/dagger input text git_author "$GITHUB_ACTOR" --environment prod_image
          /opt/hostedtoolcache/dagger/*/x64/dagger input text app_version "$(date -u +'%y.%-m.%-d+')$GITHUB_SHA" --environment prod_image
          /opt/hostedtoolcache/dagger/*/x64/dagger input text build_version "$(date -u +'%Y-%m-%dT%H.%M.%SZ')" --environment prod_image
          /opt/hostedtoolcache/dagger/*/x64/dagger input text build_url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" --environment prod_image
          /opt/hostedtoolcache/dagger/*/x64/dagger up --environment prod_image --log-format plain
```

## Where can I find the "glue code" & new pipeline config?

- glue code [`2021/dagger.mk`](https://github.com/thechangelog/changelog.com/pull/395/files#diff-9beaa194da9724432085b3b1afff0d77b0b0aecff8f73437ce01d9fff7fe07f2)
- new pipeline config [`2021/dagger/prod_image/main.cue`](https://github.com/thechangelog/changelog.com/pull/395/files#diff-75636a2a7cf6d93c2c902a4e69088de187490dcfa601f54ec499652debc04ae6)

## What happens next?

https://github.com/thechangelog/changelog.com/pull/401

## What about the rest of the comments?

If you are curious about the steps that went into this, have a look, otherwise all the important details are above the fold, meaning in this top-level comment.

---
cc @jlongtine @samalba @shykes @grouville

### CODE REVIEW

**Comment by gerhard** [comment]
My remote `DOCKER_HOST` and the Tailscale setup would be worth mentioning in the final story.

**Comment by jlongtine** [comment]
@gerhard 

> Does the existence of the `.dagger` dir imply `dagger init`?

Generally (barring changes to the `.dagger` dir), the answer ought to be yes. 

> Should `dagger init` be idempotent instead?

I personally like that idea. @aluzzardi @samalba @shykes?

> How do we spin another container for PostgreSQL, and tear it down when done? 

[`docker.#Run`](https://docs.dagger.io/reference/docker/README#dockerrun) should help for spinning up a container. I don't believe we've down any work on spinning down containers. We could probably add a `docker.#Stop`/`docker.#Rm` command. 

> This may be unrelated, but I have not seen this failure before:

I'm seeing some additional lines when I try to run this. Perhaps they'll help? It looks like it might be related to Hex Registry stuff? I wonder if Hex is assuming something about the filesystem that isn't true when that container gets run. 

```
#6 4.708 * Getting scrivener_html (https://github.com/jerodsanto/scrivener_html.git - origin/phx-1-5-9)
#6 5.627 remote: Enumerating objects: 821, done.
remote: Counting o…jects:  66% (4/6)        )        : Mix.Dep.Converger.converge/4
remote… Compressing objects: 100% (4/4)        )        .Dep.Fetcher.all/3
Re…eiving objects:   5% (42/821) (1/821)deps.get.ex:31: Mix.Tasks.Deps.Get.run/1
Rec…iving objects:  31% (255/821)/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
Receiving objects:  89% (731…821)(690/821)ll(Hex.Registry.Server, {:open, []}, 60000)
Resolvin… deltas:  24% (83/338) (0/338) raised:
Resolving deltas: 100% (338/338), done.
#6 6.382 * Getting oauth (https://github.com/tim/erlang-oauth.git)
#6 7.185 remote: Enumerating objects: 737, done.
remote: Counti…g objects:   4% (4/87)        )        ile2tab/2
remote: Counting ob…ects:  28% (25/87)        stry/server.ex:200: Hex.Registry.Server.open_ets/1
re…ote: Compressing objects:   7% (4/57)        )        .ex:85: Hex.Registry.Server.handle_call/3
Re…eiving objects:   5% (37/737) (1/737)erver.erl:721: :gen_server.try_handle_call/4
Rec…iving objects:  38% (281/737)) gen_server.erl:750: :gen_server.handle_msg/6
Receiving objects: 100% (737…737)(701/737)b.erl:226: :proc_lib.init_p_do_apply/3
Resolvin… deltas:   6% (23/369) (0/369)rver.ex:1024: GenServer.call/3
#6 7.897
#6 7.897 23:49:14.072 [error] GenServer Hex.Registry.Server terminating
#6 7.897 ** (MatchError) no match of right hand side value: {:error, {{:EXIT, {:function_clause, [{:disk_log_sup, :start_link, [], [file: 'disk_log_sup.erl', line: 26]}, {:supervisor, :do_start_child_i, 3, […
#6 7.897     (kernel 8.0) disk_log_server.erl:142: :disk_log_server.ensure_started/0
#6 7.897     (kernel 8.0) disk_log_server.erl:52: :disk_log_server.open/1
#6 7.897     (stdlib 3.15) ets.erl:990: :ets.file2tab/2
#6 7.897     (hex 0.21.2) lib/hex/registry/server.ex:200: Hex.Registry.Server.open_ets/1
#6 7.897     (hex 0.21.2) lib/hex/registry/server.ex:85: Hex.Registry.Server.handle_call/3
#6 7.897     (stdlib 3.15) gen_server.erl:721: :gen_server.try_handle_call/4
#6 7.897     (stdlib 3.15) gen_server.erl:750: :gen_server.handle_msg/6
#6 7.897     (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
#6 7.897 Last message (from #PID<0.94.0>): {:open, []}
#6 7.897 State: %{closing_fun: nil, ets: nil, fetched: #MapSet<[]>, path: nil, pending: #MapSet<[]>, waiting: %{}}
#6 7.897 Client #PID<0.94.0> is alive
#6 7.897
#6 7.897     (stdlib 3.15) gen.erl:233: :gen.do_call/4
#6 7.897     (elixir 1.12.0) lib/gen_server.ex:1021: GenServer.call/3
#6 7.897     (hex 0.21.2) lib/hex/remote_converger.ex:18: Hex.RemoteConverger.converge/2
#6 7.897     (mix 1.12.0) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
#6 7.897     (mix 1.12.0) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
#6 7.897     (mix 1.12.0) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
#6 7.897     (mix 1.12.0) lib/mix/tasks/deps.get.ex:31: Mix.Tasks.Deps.Get.run/1
#6 7.897     (mix 1.12.0) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
#6 7.908 ** (exit) exited in: GenServer.call(Hex.Registry.Server, {:open, []}, 60000)
#6 7.908     ** (EXIT) an exception was raised:
#6 7.908         ** (MatchError) no match of right hand side value: {:error, {{:EXIT, {:function_clause, [{:disk_log_sup, :start_link, [], [file: 'disk_log_sup.erl', line: 26]}, {:supervisor, :do_start_child…
#6 7.908             (kernel 8.0) disk_log_server.erl:142: :disk_log_server.ensure_started/0
#6 7.908             (kernel 8.0) disk_log_server.erl:52: :disk_log_server.open/1
#6 7.908             (stdlib 3.15) ets.erl:990: :ets.file2tab/2
#6 7.908             (hex 0.21.2) lib/hex/registry/server.ex:200: Hex.Registry.Server.open_ets/1
#6 7.908             (hex 0.21.2) lib/hex/registry/server.ex:85: Hex.Registry.Server.handle_call/3
#6 7.908             (stdlib 3.15) gen_server.erl:721: :gen_server.try_handle_call/4
#6 7.908             (stdlib 3.15) gen_server.erl:750: :gen_server.handle_msg/6
#6 7.908             (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
#6 7.908     (elixir 1.12.0) lib/gen_server.ex:1024: GenServer.call/3
#6 7.908     (hex 0.21.2) lib/hex/remote_converger.ex:18: Hex.RemoteConverger.converge/2
#6 7.908     (mix 1.12.0) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
#6 7.908     (mix 1.12.0) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
#6 7.908     (mix 1.12.0) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
#6 7.908     (mix 1.12.0) lib/mix/tasks/deps.get.ex:31: Mix.Tasks.Deps.Get.run/1
#6 7.908     (mix 1.12.0) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
#6 7.908     (elixir 1.12.0) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
#6 7.910
#6 7.910 23:49:14.152 [error] GenServer Hex.UpdateChecker terminating
#6 7.910 ** (stop) exited in: GenServer.call(Hex.Registry.Server, :last_update, 60000)
#6 7.910     ** (EXIT) an exception was raised:
#6 7.910         ** (MatchError) no match of right hand side value: {:error, {{:EXIT, {:function_clause, [{:disk_log_sup, :start_link, [], [file: 'disk_log_sup.erl', line: 26]}, {:supervisor, :do_start_child…
#6 7.910             (kernel 8.0) disk_log_server.erl:142: :disk_log_server.ensure_started/0
#6 7.910             (kernel 8.0) disk_log_server.erl:52: :disk_log_server.open/1
#6 7.910             (stdlib 3.15) ets.erl:990: :ets.file2tab/2
#6 7.910             (hex 0.21.2) lib/hex/registry/server.ex:200: Hex.Registry.Server.open_ets/1
#6 7.910             (hex 0.21.2) lib/hex/registry/server.ex:85: Hex.Registry.Server.handle_call/3
#6 7.910             (stdlib 3.15) gen_server.erl:721: :gen_server.try_handle_call/4
#6 7.910             (stdlib 3.15) gen_server.erl:750: :gen_server.handle_msg/6
#6 7.910             (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
#6 7.910     (elixir 1.12.0) lib/gen_server.ex:1024: GenServer.call/3
#6 7.910     (hex 0.21.2) lib/hex/update_checker.ex:110: Hex.UpdateChecker.check_update?/0
#6 7.910     (hex 0.21.2) lib/hex/update_checker.ex:29: Hex.UpdateChecker.handle_cast/2
#6 7.910     (stdlib 3.15) gen_server.erl:695: :gen_server.try_dispatch/4
#6 7.910     (stdlib 3.15) gen_server.erl:771: :gen_server.handle_msg/6
#6 7.910     (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
#6 7.910 Last message: {:"$gen_cast", :start_check}
#6 7.910 State: %{done: false, from: nil, reply: nil, started: false}
4:49PM FTL failed to up environment: task failed: process "/bin/sh -c   mix do deps.get, deps.compile, test" did not complete successfully: exit code: 1
```

**Comment by samalba** [comment]
> How do we spin another container for PostgreSQL, and tear it down when done?

You can spin-up many containers from the same dagger cue config. You cannot tear it down for now, I would advise (as a tmp solution) to add a `docker rm -f XXX` in a `finally:` statement (ci yaml).

Not sure about the compile issue, do you have a requirement on the arch? It's possible to specify a custom arch with the latest dagger, not sure if that helps. You should be able to repro this locally with a `dagger up` on the same config, it'd be easier to debug.

**Comment by shykes** [comment]
One explanation might be that binary objects (like `c_src/blocks.o` in the quoted error) were built separately on the client machine (perhaps a Mac), and were then mounted into the Dagger build, where `cc` attempts to load them but fails, because they are built from the wrong architecture (eg. `Darwin/arm` vs `Linux/amd64`).

**Comment by gerhard** [comment]
Thanks all, the above comments have been helpful.

I am able to get deps & compile them, even though compilation doesn't seem to be cached as expected. I'm also not sure how to `docker rm` the test db container, as there is no container showing on the system, which I think is related to Dagger using Buildkit for containers, which do not show in `docker` commands. This captures my current blockers: https://github.com/thechangelog/changelog.com/pull/395/commits/572a0b0095f248088073f0762cf1ebd4c024d0f1

**Comment by gerhard** [comment]
Current state:
image

image

Subsequent run:

image

`OTEL_EXPORTER_JAEGER_ENDPOINT` integration is sweet:
image

**Comment by gerhard** [comment]
The last step is to publish the image to DockerHub.

Current state:
image

Compare the above 37s cached run with the CircleCI equivalent (remove 60s for the image publishing part):
image

**Comment by gerhard** [comment]
Current state:
image

The commit above has all the details

**Comment by gerhard** [comment]
Current state:
image

**Comment by jlongtine** [comment]
@gerhard Was having some issues running this on my M1 Pro, got an AMD linux machine up and running , so I'll try to reproduce more successfully this weekend/next week. Feel free do ping me on Dagger Discord if you need anything.

**Comment by gerhard** [comment]
> @gerhard Was having some issues running this on my M1 Pro, got an x64 Linux EC2 instance up and running

That's right, our Makefiles do not have ARM support, only x86 currently. Thanks for working around it!

> I'll try to reproduce more successfully this weekend/next week.

Thank you, I'm taking another small step now, will update with progress shortly.

**Comment by gerhard** [comment]
Current state:

image

Next step: compare the resulting `dagger` tag to `latest` for `thechangelog/changelog.com` image. Pretty sure the one tagged with `dagger` was built incorrectly, but let's check out the difference. Note that I've been using `echo` instead of the actual commands to speed the build, and locally I have removed the `echo` statements.

**Comment by gerhard** [comment]
I cannot run the container image:

```
docker run -it docker.io/thechangelog/changelog.com:dagger@sha256:06c59707da04889c88387fbe4e5ca6e9574c7946175ed88675e6a0b9f717298f bash
Unable to find image 'thechangelog/changelog.com:dagger@sha256:06c59707da04889c88387fbe4e5ca6e9574c7946175ed88675e6a0b9f717298f' locally
docker.io/thechangelog/changelog.com@sha256:06c59707da04889c88387fbe4e5ca6e9574c7946175ed88675e6a0b9f717298f: Pulling from thechangelog/changelog.com
Digest: sha256:06c59707da04889c88387fbe4e5ca6e9574c7946175ed88675e6a0b9f717298f
Status: Downloaded newer image for thechangelog/changelog.com@sha256:06c59707da04889c88387fbe4e5ca6e9574c7946175ed88675e6a0b9f717298f
WARNING: The requested image's platform (unknown) does not match the detected host platform (linux/amd64) and no specific platform was requested
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown.
```

And there is no history:

```
docker history --no-trunc docker.io/thechangelog/changelog.com:dagger@sha256:06c59707da04889c88387fbe4e5ca6e9574c7946175ed88675e6a0b9f717298f
IMAGE     CREATED   CREATED BY   SIZE      COMMENT
```

Something must be off here: https://github.com/thechangelog/changelog.com/blob/88da1f85d9192f8ff21a7c0fea4cb14f8d9e4cb7/2021/dagger/ci/ci.cue#L161-L164

**Pull request merged**
